### ISSUE TITLE
createMany

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#34]
Hi,

We have been talking `removeMany, updateMany` but I might have forget to mention `createMany` or is this feature already exist in `ottoman`?

If not, then this is also one feature that is of the same importance to `removeMany, updateMany`

I guess the API would be (something like)

```js
// single object
const single = { name: 'a' };
create(single);

// multiple object
const multiple = [
	{ name: 'a' },
	{ name: 'b' },
]
create(multiple);
```

Thanks!

**Comment by AV25242** [comment]
https://github.com/couchbaselabs/node-ottoman/issues/336 is created

**Comment by bwgjoseph** [comment]
Thanks.

Can I check for couchbase, does it internally has a bulkWrite feature for the createMany, updateMany and removeMany? 

Or is it that internally, ottoman still process it individually?

**Comment by httpJunkie** [comment]
Hi Joseph, so the NodeJS SDK has a page that describes how this bulk writes, batching process is automatic and done optimally and happens internally and is highly efficient.

https://docs.couchbase.com/nodejs-sdk/current/howtos/concurrent-async-apis.html#batching

Specifically, pay attention to is this part:

**As Node.js inherently performs all operations in an asynchronous manner, no special implementation is required in order to enable batching. Simply perform a number of operations simultaneously and they will be batched on the network. This happens internally and is highly efficient.**

I hope this answers your question. Let me know if you have any more questions about this topic specifically.

**Comment by bwgjoseph** [comment]
Thanks @httpJunkie 

So does that mean that when I call `createMany(arrayOfDocs)`, `ottoman` internally converts to batching?

```js
await Promise.all([
    collection.insert(doc1)
    collection.insert(doc2)
    // and so on
]);
```

**Comment by httpJunkie** [comment]
We create batching up to 100 operations and this batch will be executed by KV operations against the server. So if you want to process 120 documents, internally we set up a batch of 100 promises and wait for them to resolve and then create another batch of 20 promises and wait for them to resolve. Then we return an object letting the user know of the success or error.

119 succeeded 1 error potentially could be returned back to the user is one of the document creations were to fail.

**Comment by bwgjoseph** [comment]
While testing this with asserting `GenericManyQueryResponse`, noticed that when one of the create operation fails, the error returns errors as `undefined`. Take a look at this test case

https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/c3e8cc43a2f5d38bb5960f517e97bf5c97c676f6/test/ts/createMany.test.ts#L51-L91

Here's the response

```js
GenericManyQueryResponse {
  status: 'SUCCESS',
  message: { modified: 1, match_number: 2, errors: [ undefined ] }
}
```

Same issue goes for `updateMany` and `removeMany`

**Comment by AV25242** [comment]
@bwgjoseph  currently errors returns you back Id of the document, but in case of CreateMany there will not be any Id, still thinking what it should return back. Probably thats why its returning back an undefined  i think.

**Comment by bwgjoseph** [comment]
This is somewhat related to my question on #40 

If the errors is not returning the error-message but the id of the item, then for `createMany`, like you mention, will not have any `id` to return. But in what kind of scenario, would `updateMany` or `removeMany` operation return the `id` in the error?

**Comment by gsi-chao** [comment]
This error should be fixed in the next build, the answer will be:
`{
  "status": "FAILED",
  "message": {
    "success": 1,
    "match_number": 2,
    "errors": [
      {
        "payload": {
          "callsign": "Hawk"
        },
        "status": "FAILED",
        "exception": "ValidationError",
        "message": "Property name is required"
      }
    ]
  }
}`

**Comment by gsi-chao** [comment]
Also add that the GenericManyQueryResponse class will be renamed to ManyQueryResponse

**Comment by bwgjoseph** [comment]
Unable to verify due to `ManyQueryResponse` not fixed as mentioned in #40
