### ISSUE TITLE
GenericManyQueryResponse query

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#40]
Hi,

Based on the [GenericManyQueryResponse](https://v2.ottomanjs.com/classes/genericmanyqueryresponse.html) docs, the message is defined as `match_number, success and errors`.

Would like to know what exactly does `match_number` information gives, and would there be any case that it will defer from the one I pass in? For example, `model.createMany([item1, item2])`, would the `match_number` ever return NOT EQUAL `2`? I assume that the `match_number` refers to the number of items being passed in the query?

And what kind of `errors` are to be expected, if one (or more) of the doc fails to create/update/remove?

Also, the `status` field declare either `SUCCESS` or `FAILED`, and if the event where `model.createMany([item1, item2])` and `item1` can be created, and `item2` fails, what should be the `status`? I think the current one are all still defining as `SUCCESS`

I couldn't find any information on the documentation regarding this

Thanks!

**Comment by AV25242** [comment]
This is going to be revamped we already have [tickets](https://github.com/couchbaselabs/node-ottoman/issues/355) for this open. Summary

Status will be FAILURE even if one of the operation fails
erros will return back useful error messages and exception type

**Comment by AV25242** [comment]
fixed with alpha.14 please review

**Comment by josephstgh** [comment]
Hi, some feedback

1. import

Currently, the import is via `/lib/types/handler`

```js
import { SearchConsistency } from 'ottoman';
import { ManyQueryResponse } from 'ottoman/lib/types/handler';
```

Is this intended? Should it be re-exported internally, so it's imported via `ottoman` or something? I'm not exactly sure if there's any difference though

2. `ManyQueryResponse`, `StatusExecution`, etc is a `Class` type. Should it not be a `interface` or `type`?

```js
// ManyQueryResponse is a Class
const response: ManyQueryResponse = await Airplane.createMany[1,2,3];

const expected: ManyQueryResponse = {
	status: 'SUCCESS',
	message: {
		success: 1,
		match_number: 2,
		errors: []
	}
};
```

3. You mentioned that the status will be changed to `FAILURE` but it's still `FAILED`. Would it be changed?

4. What is the `model` in the error message? Is it something internal to `ottoman/Couchbase`? 

```js
{
	exception: 'ValidationError',
	message: 'Property name is required, Property model is required',
	payload: {
		callsign: 'Hawk'
	},
	status: 'FAILED'
},
```

5. Referring back to Point 2, seem like because it is declared as `Class`, I'm not able to assert correctly. It kind of expecting a `StatusExecution` object

![image](https://user-images.githubusercontent.com/47846485/105441666-039dd780-5ca4-11eb-9d2b-5f38223536dc.png)

I'm declaring as

```js
const expected: ManyQueryResponse = {
	status: 'FAILED',
	message: {
		success: 0,
		match_number: 2,
		errors: [
			{
				exception: 'ValidationError',
				message: 'Property name is required, Property model is required',
				payload: {
					callsign: 'Hawk'
				},
				status: 'FAILED'
			},
			{
				exception: 'ValidationError',
				message: 'Property callsign is required, Property model is required',
				payload: {
					name: 'Couchbase Airline'
				},
				status: 'FAILED'
			}
		]
	}
};
```

**Comment by gsi-chao** [comment]
Hi @josephstgh 
1- In the next version(2.0.0-alpha.15) you can import IManyQueryResponse, IStatusExecution from the root of 'ottoman'.
2- You can use now IManyQueryResponse, IStatusExecution as an interface
3- It was my mistake, the correct state is FAILED.
4- Sound like a bug, let me review.
5- See point 1.

**Comment by httpJunkie** [comment]
Should this be FAILURE rather than FAILED, considering some of the operations may have succeeded?

I think it might make more sense.

**Comment by gsi-chao** [comment]
@josephstgh 
Regarding point 4, I have reviewed your test and the airplane schema has a field called **model** that is required. This is why this message **"Property model is required"**

As @httpJunkie  comments we are going to change the status FAILED to FAILURE.

**Comment by bwgjoseph** [comment]
You're right, not sure why I missed that. 

Thank you for pointing out.

Will be waiting for `alpha.15` to test out the new fixes.

**Comment by AV25242** [comment]
@bwgjoseph  the ones post discussion that were defects should be fixed in aplha.16 release.

**Comment by bwgjoseph** [comment]
Hi, 

Referring to this https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/40#issuecomment-765095800

1. Not fixed
2. Not fixed
3. Fixed
4. Fixed (My error)
5. Not fixed

**Comment by AV25242** [comment]
@bwgjoseph please check alpha16.2 released today

**Comment by bwgjoseph** [comment]
Hi,

1. Fixed
2. Partial Fixed (See 5)
5. Not Fixed

I suspect that because it's returning an instance of the `StatusExecution class` which is created via `constructor`, the return type reflect differently. See [typescript-play](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=24&pc=46#code/JYOwLgpgTgZghgYwgAgMrIN4ChnIA5wCeANgPZwAmAXGmFKAOYA0OyAthAM6dwMQ2o6jFgF8sWBMTjdacMAFdOmVpzACA3KwSkQqqPIRhSUABQES5asj3D2XHnxo2QDAJTLcuMAAtgnAHSqyAC8mPhEZJRMdty8KCKauGKsRgBSnDom7tieyFAQClAgyD5+gWCJyGLJAPQ1Jb5KfshwyJLSTbpgcCBIWHXW3qTyxBTIIKRgeQXyRQ1+EjoZxBD+ZAwmIBAA7rIKnCYA5HjEh9GHbJyHrq6a-fWlStvAxMTIAEYo+YXF0g0o2ig+UMJUIeAg90Gw1G0x+804kMeyGaACtFFMesgIAAPOBsE4QaIUHRTUogADW8ORSh8X2ADG8U22REWulIKzWpA2W12gjkiiOJzOyAuV1c-jSGRAWVuQA)

Also, the return types were not changed to return the `interface`  like `IManyQueryResponse` in https://github.com/couchbaselabs/node-ottoman/blob/master/src/model/model.ts

**Comment by gsi-chao** [comment]
@bwgjoseph Can you put here the specific test that fails?

**Comment by bwgjoseph** [comment]
@gsi-chao 

This is the test case

https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/5eb73b5f6c554929c93a12f3e5a90ff1a4a5c036/test/ts/createMany.test.ts#L164

**Comment by gsi-chao** [comment]
@bwgjoseph 
I create a test similar to yours and it all works like a charm. You need to use the interface IManyQueryResponse instead of ManyQueryResponse. The ManyQueryResponse class implements this interface.

**Comment by gsi-chao** [comment]
```
it('ottoman - should not create new doc when using partial doc', async () => {
        const Airplane = getOttomanModel();
        const response: IManyQueryResponse = await Airplane.createMany([
            {
                callsign: 'Hawk',
            },
            {
                name: 'Couchbase Airline',
            }
        ]);

        const expected: IManyQueryResponse = {
            status: 'FAILED',
            message: {
                success: 0,
                match_number: 2,
                errors: [
                    {
                        exception: 'ValidationError',
                        message: 'Property name is required, Property model is required',
                        payload: {
                            callsign: 'Hawk'
                        },
                        status: 'FAILED'
                    },
                    {
                        exception: 'ValidationError',
                        message: 'Property callsign is required, Property model is required',
                        payload: {
                            name: 'Couchbase Airline'
                        },
                        status: 'FAILED'
                    }
                ]
            }
        };

        assert.strictEqual(response.status, expected.status);
        assert.deepStrictEqual(response.message, expected.message);

        const find = await Airplane.find(
            {},
            {
                consistency: SearchConsistency.LOCAL
            });
        assert.strictEqual(find.rows.length, 0);

        await removeDocuments();
    });
```
This should work for you. I miss something?

**Comment by josephstgh** [comment]
Hi @gsi-chao,

That's my bad. I have just pushed in a new commit to use the interface. Previously, I had tried on `IManyQueryResponse` but it was still triggering error, hence, I did not push in the commit.

Even when using `IManyQueryResponse`, it still have the issue

This is what I'm getting even when using `IManyQueryResponse`

![image](https://user-images.githubusercontent.com/47846485/108007766-b3632c80-7039-11eb-85cf-71d7caf7575d.png)

**Comment by gsi-chao** [comment]
I suggest you compare the plain JSON objects instead of the javascript object, in other case you need to create the ManyQueryResponse object instance.
Example
```
const expected: IManyQueryResponse = new ManyQueryResponse('FAILURE', {
      success: 0,
      match_number: 2,
      errors: [
        new StatusExecution(
          {
            callsign: 'Hawk',
          },
          'FAILURE',
          'ValidationError',
          'Property name is required, Property model is required',
        ),
      ],
    });
```

**Comment by httpJunkie** [comment]
@gsi-chao can you give an example considering the response above?

**Comment by gsi-chao** [comment]
```
test('Test Create Many Errors JSON Explain ', async () => {
  const Box = model('Box', { name: String, price: { required: true, type: Number } });
  await startInTest(getDefaultInstance());
  const docs = [{ name: 'Xbox', price: 10 }, { name: 'Yellow Box' }];
  const queryResult: IManyQueryResponse = await Box.createMany(docs);

  const queryResultJson: IManyQueryResponse = {
    status: 'FAILURE',
    message: {
      success: 1,
      match_number: 2,
      errors: [
        {
          payload: {
            name: 'Yellow Box',
          },
          status: 'FAILURE',
          exception: 'ValidationError',
          message: 'Property price is required',
        },
      ],
    },
  };
  expect(JSON.stringify(queryResult)).toStrictEqual(JSON.stringify(queryResultJson));
  const cleanUp = async () => await Box.removeMany({ _type: 'Box' });
  await cleanUp();
});

test('Test Create Many Errors Class Explain ', async () => {
  const Box = model('Box', { name: String, price: { required: true, type: Number } });
  await startInTest(getDefaultInstance());
  const docs = [{ name: 'Xbox', price: 10 }, { name: 'Yellow Box' }];
  const queryResult: IManyQueryResponse = await Box.createMany(docs);

  const queryResultClass = new ManyQueryResponse('FAILURE', {
    success: 1,
    match_number: 2,
    errors: [
      new StatusExecution(
        {
          name: 'Yellow Box',
        },
        'FAILURE',
        'ValidationError',
        'Property price is required',
      ),
    ],
  });

  expect(queryResult).toStrictEqual(queryResultClass);
  const cleanUp = async () => await Box.removeMany({ _type: 'Box' });
  await cleanUp();
});
```

**Comment by bwgjoseph** [comment]
Hi @gsi-chao,

Thanks for the sample, and it provides more clarity for me.

I haven't had chance to test the new lean feature yet, but in this case, would using `lean` allow me to assert without `stringify-ing` or `constructing new instance`?

```js
// if using lean option, can I assert like such
assert.deepStrictEqual(response, expected);
```

Thanks

**Comment by gsi-chao** [comment]
The lean feature is only for the documents(Models intance). In this case, ManyQueryResponse is a util class and doesn't have this lean feature.

**Comment by bwgjoseph** [comment]
Thanks. 

Based on my memory, and I think that Models also return as a class which is why the response is also something along

```js
_Model {
  // fields
}
```

Am I right?

Also, in that case, I'm wondering if in future, there could be a possibility of adding via options (like `lean: true`) that returns the plan object rather than class instance. Is there any cons to providing/having these? Although, don't have any very specific use-case right off my mind now

**Comment by AV25242** [comment]
@bwgjoseph can this be moved on to the ticket for lean you already have ,so that this ticket can be evaluated and closed :) ?

**Comment by bwgjoseph** [comment]
Continue discussion to #43
