### ISSUE TITLE
expose ModelOptions

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#66]
Hi,

Similar to #62, importing `ModelOptions` is only via (currently)

```js
import { ModelOptions } from 'ottoman/lib/types/model/interfaces/create-model.interface';
```

**Comment by AV25242** [comment]
Should be available with next release

**Comment by AV25242** [comment]
https://github.com/couchbaselabs/node-ottoman/issues/475

**Comment by httpJunkie** [comment]
Fixed w/ alpha 29

**Comment by bwgjoseph** [comment]
This is not fixed yet

![image](https://user-images.githubusercontent.com/37484538/119024343-8b3aef00-b9d5-11eb-83a5-e03a2fd06a42.png)

**Comment by AV25242** [comment]
Reopened the issue

**Comment by AV25242** [comment]
@bwgjoseph can you please check ?

**Comment by bwgjoseph** [comment]
@AV25242 The change is made after `beta.1` release, so it's not fixed yet

`beta.1` released on May 23, 2021
The fix is done on Jun 2, 2021

**Comment by AV25242** [comment]
Let me confirm on the comment from our team, thanks for pointing that out

**Comment by AV25242** [comment]
Yep you are right it will be next release.

**Comment by AV25242** [comment]
this should be available now with beta 2

**Comment by bwgjoseph** [comment]
Verified
