### ISSUE TITLE
[regression?] findOneAndUpdate

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#73]
Hi,

While re-running my test suite, I noticed that running `findOneAndUpdate` seems to not update any of my fields.

These are the setup

```js
const defaultDate = new Date();

const baseSchema = new Schema({
    createdAt: {
        type: Date,
        default: () => defaultDate,
        immutable: true,
    },
    updatedAt: {
        type: Date,
        default: () => defaultDate,
    },
    createdBy: {
        type: String,
        default: () => 'Joseph',
        immutable: true,
    },
    updatedBy: {
        type: String,
        default: () => 'Joseph'
    }
});

const schema = new Schema({
    name: {
        type: String,
        required: true,
    },
    operational: {
        type: Boolean,
        default: true
    },
}).add(baseSchema);

const opt = {
    name: 'hello',
    operational: true,
};
```

This is the test

```js
const Immutable3Model = ottoman.getModel('immutable3') || ottoman.model('immutable3', schema, { idKey: '_id' });
const schemaData = new Immutable3Model(opt);

const created = await Immutable3Model.create(schemaData);
console.log(JSON.stringify(created, null, 2));
const changeDate = new Date();
const findOneAndUpdate = await Immutable3Model.findOneAndUpdate({ _id: created._id }, {
    name: 'test',
    createdAt: changeDate,
    createdBy: 'Edwin',
    updatedAt: changeDate,
    updatedBy: 'Edwin',
});
console.log(JSON.stringify(findOneAndUpdate, null, 2));
```

This is the output

```js
// after created
{
  "name": "hello",
  "operational": true,
  "createdAt": "2021-05-07T10:39:14.616Z",
  "updatedAt": "2021-05-07T10:39:14.616Z",
  "createdBy": "Joseph",
  "updatedBy": "Joseph",
  "_id": "21fb0451-60d8-4948-ae89-a8bd75526ff0",
  "_type": "immutable3"
}
// after findOneAndUpdate
{
  "_id": "21fb0451-60d8-4948-ae89-a8bd75526ff0",
  "createdAt": "2021-05-07T10:39:14.616Z",
  "createdBy": "Joseph",
  "name": "hello",
  "operational": true,
  "updatedAt": "2021-05-07T10:39:14.616Z",
  "updatedBy": "Joseph"
}
```

Thanks

**Comment by bwgjoseph** [comment]
Nope, it does not work. And it shouldn't need to pass in any way since it's a single API call, and the result from this call should give back the correct response without `consistency` defined

**Comment by AV25242** [comment]
This should be fixed with the next release.

**Comment by httpJunkie** [comment]
Fixed w/ alpha 29

**Comment by bwgjoseph** [comment]
This is not fixed yet. I'm still getting facing the same issue

**Comment by gsi-ariam** [comment]
```
const findOneAndUpdate = await Immutable3Model.findOneAndUpdate(
  { _id: created._id },
  {
    name: 'test',
    createdAt: changeDate,
    createdBy: 'Edwin',
    updatedAt: changeDate,
    updatedBy: 'Edwin',
  },
  // { new: true },👈🏼👈🏼👈🏼 To get document updated
);
```

Please check this:
[Ottoman findOneAndUpdate doc `new` option](https://v2.ottomanjs.com/interfaces/findoneandupdateoption.html#optional-new)

**Comment by bwgjoseph** [comment]
Thanks! I missed that, it working now
