### ISSUE TITLE
take in generic for ManyQueryResponse

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#82]
Hi,

Possible to accept generic for ManyQueryResponse?

```js
createMany<Doc = T>(docs: Doc[] | Doc): Promise<ManyQueryResponse>;
removeMany<Doc = T>(filter?: LogicalWhereExpr<Doc>, options?: FindOptions): Promise<ManyQueryResponse>;
updateMany<Query = T>(filter?: LogicalWhereExpr<Query>, doc?: T | Partial<T>, options?: UpdateManyOptions): Promise<ManyQueryResponse>;
```

Notice the `Promise<ManyQueryResponse>` where we can pass return back `Promise<ManyQueryResponse<T>>` instead

This allows better typing like such

![image](https://user-images.githubusercontent.com/37484538/119016566-aa814e80-b9cc-11eb-8094-8cba6bc76e60.png)

So that instead of using `any[]`, we can return `T[]`

```js
// instead of
export interface ManyResponse {
    data?: any[];
    match_number: number;
    success: number;
    errors: StatusExecution[];
}

// become
export interface ManyResponse<T> {
    data?: T[];
    match_number: number;
    success: number;
    errors: StatusExecution[];
}
```

And the `data` probably don't set it to optional? Seem like the response always return an empty array of data like such

```js
{
         "message": {
          "data": []
           "errors": []
           "match_number": 0
           "success": 0
         }
```

Thanks!

**Comment by AV25242** [comment]
Yeah data is intentional to be given out as opposed to an option

**Comment by AV25242** [comment]
you mean optional ? right now its non-optional

**Comment by bwgjoseph** [comment]
I mean the interface

```js
// should be
export interface ManyResponse {
    // note, no ?
    data: any[];
    match_number: number;
    success: number;
    errors: StatusExecution[];
}

// instead of
export interface ManyResponse {
    data?: any[];
    match_number: number;
    success: number;
    errors: StatusExecution[];
}
```

Since that, all multi-methods will always return `data`, it doesn't make sense to make it optional unless there is case where `data` is not being returned

**Comment by bwgjoseph** [comment]
I was testing this with `beta.2` but I'm not sure how to take advantage of the recent change to the generic type

So if I don't specify any types, then it gives me `any` which is correct

![image](https://user-images.githubusercontent.com/37484538/123140406-d4c1a280-d489-11eb-8237-e1ac1f3f5f89.png)

Same thing if I only specify the request type (doc)

![image](https://user-images.githubusercontent.com/37484538/123140486-ec992680-d489-11eb-85c6-ebcbffc5f421.png)

So if I pass in the `request, response` type (doc, result), it will infer correctly

![image](https://user-images.githubusercontent.com/37484538/123140659-21a57900-d48a-11eb-8721-b97c7cd65bbc.png)

But then when I tries to access `data`, it will infer back to `any`

![image](https://user-images.githubusercontent.com/37484538/123140743-3bdf5700-d48a-11eb-9ef8-c20382e6e688.png)

Any idea?

**Comment by AV25242** [comment]
@bwgjoseph  I am a bit lost here in general. What was this ticket created for and have we addressed whats needed for this ticket or did we derail this one ? :)  if so can you assist cleaning this one up probably by opening another ticket and closing this one. This one seems to be overloaded if I am not wrong ? Or this one seems to be closer to the finish line (which I doubt ) ?

**Comment by bwgjoseph** [comment]
I think whatever was done did not resolve this issue, and that's why I'm trying to clarify. 

Coming from a developer perspective, it seems like this wasn't done right because it is not inferring the correct type even when I pass in the `type` as seen in `createMany<AirplaneInterface, AirplaneInterface>` but when I try to use the `response` object, the `type` is lost and as seen in the last picture, it is now become `any` instead of the `AirplaneInterface` that I passed in

If done correctly, or at least what I think so, the `data` type should auto inferred as `AirplaneInterface` instead of `any`

Based on this PR https://github.com/couchbaselabs/node-ottoman/pull/506, I think something is still not done right that's why it's not inferred correctly. Hence, this issue is still not consider as resolved

**Comment by gsi-alejandro** [comment]
@AV25242 @bwgjoseph 

@bwgjoseph was right, something was wrong. I declare the generics correctly but I forgot to pass this generic value into inherited components (`extends QueryResponse<ManyResponse<T>>`), therefore data was losing the type definition provided.

I already fixed it and will be ready to ship the next release. 
![image](https://user-images.githubusercontent.com/15661442/123696279-903b5b80-d829-11eb-873f-503cdc05ae6b.png)

Thanks to both of you.

**Comment by AV25242** [comment]
Thanks @gsi-alejandro , @bwgjoseph  this should be available in the next release.

**Comment by AV25242** [comment]
[v2.0.0-beta.3 released]( https://www.npmjs.com/package/ottoman/v/2.0.0-beta.3)

**Comment by bwgjoseph** [comment]
Hi @gsi-alejandro,

Not sure if I'm still missing something here, but it still doesn't seem to be able to infer correctly.

This is better now that it inters the interface correctly.

![image](https://user-images.githubusercontent.com/37484538/126025965-54eb97f0-a3b7-4f5d-a481-1f5b937dc31d.png)

But it's not able to show the fields

![image](https://user-images.githubusercontent.com/37484538/126025981-c660fc5a-0371-4576-b87a-224154c14bce.png)

I think this should be able to show the fields

![image](https://user-images.githubusercontent.com/37484538/126026213-3b64b5d3-a836-4163-9a92-aae1c8cf9be1.png)

**Comment by gsi-alejandro** [comment]
hi @bwgjoseph 

This issue will be fixed available next release (the fix was already merged into the master branch)

**Comment by AV25242** [comment]
We released [Ottoman beta.9](https://www.npmjs.com/package/ottoman/v/2.0.0-beta.9) today please verify

**Comment by bwgjoseph** [comment]
Seem to work now

![image](https://user-images.githubusercontent.com/37484538/134806331-6a5ee37e-e8d8-4558-87fc-3a93a9df0f87.png)
